### ISSUE TITLE
[Bug] Notifications with the same collapse ID do not get updated

### ISSUE THREAD

**Issue by infernoboy** [Nepeta/StackXI#47]
Only the first notification of a series with the same ~~thread ID~~ collapse-id will appear in notification center when StackXI is enabled. The notification will appear as a banner as expected, but won't be in NC. I don't know how one can easily reproduce this; I have my own app that uses ~~thread IDs~~ collapse-ids that I noticed the issue on.

Edit: Wanted to point out that after respringing, StackXI will show those notifications, but new ones once again won't appear.

**Comment by Ominousness** [comment]
@infernoboy Could you send me that app? Twitter: @TheOminousness.

**Comment by infernoboy** [comment]
It's an app I created for personal use with a very specific use case. I cannot distribute it. In the StackXI source you have test notifications. Can you provide thread IDs to those?

**Comment by Ominousness** [comment]
@infernoboy Sure, any particular threadIDs that cause the issue or any repeating ones?

**Comment by infernoboy** [comment]
The thread IDs I use look like this: 2018121108

I don't think its value matters though. Can have it so mobile SMS sends a few from one ID then a few more with a different ID. I'll try playing with it too to see if the issue can be reproduced with this method.

**Comment by Ominousness** [comment]
@infernoboy Okay, I'll check it out as well.

For the debug mode to activate you just need to build StackXI with DEBUG=1 (default).

**Comment by infernoboy** [comment]
If you still need help reproducing the issue, I created a small app and backend to do so. You can find it here: https://github.com/infernoboy/apns-echo/releases/tag/0.0.1 

I've never distributed an app before so I assume you'll have to side-load it. Hopefully it'll work… 

In the app, you can simply press "Push Back". Exit the app within 10 seconds an you'll see a banner with the thread ID and message. Then, a second later, your message appended with "(UPDATED THREAD)". Now, look at the notification center and notice the "UPDATED THREAD" notification isn't there, only the first one is.

**Comment by Ominousness** [comment]
Thank you.

**Comment by infernoboy** [comment]
I mistakenly mixed up thread-id and collapse-id. The actual bug results from setting a collapse-id in an APN payload. The app and backend I made for testing this is using collapse-id, though. Just got confused and thought it was the same as thread-id. StackXI works perfectly fine with thread-ids (I even made a version of StackXI for myself that organizes stacks by threads!)

**Comment by Nepeta** [comment]
@infernoboy If you're interested in contributing you could push some of your code to be included as an option :) I'm closing the issue, thank you.

**Comment by infernoboy** [comment]
Erm, the issue with collapse-id still exist, though; I just mixed up the terms. Should it be a new issue instead or do you have no plans to fix it =[ ?

**Comment by Nepeta** [comment]
@infernoboy I'll reopen it and change the title.

**Comment by Nepeta** [comment]
Should be an easy fix now that I know what to debug :P I think I know what i need to hook.

**Comment by Nepeta** [comment]
@infernoboy Could you give it another try on 0.4.8? I'm not sure if it's completely fixed.

**Comment by infernoboy** [comment]
Quick test with the sample app works fine now. Will test more with the primary app i use it for.

**Comment by infernoboy** [comment]
Seems to be working great now, thank you!

**Comment by Nepeta** [comment]
Issue solved then. Closing.
