### ISSUE TITLE
[Feature] Delete all notifications at once ("Clear All" button [x])

### ISSUE THREAD

**Issue by D3m3rion** [Nepeta/StackXI#5]
Since the notification history seems to be broken, and notifications aren't sorted by iOS' stock "older notifications", "yesterday" etc, the X doesn't appear, so you can't force-touch it to remove all notifications.
There might be a workaround with Activator, but I'd rather have the X button back somehow, or another way, like right swiping any notification to reveal an option to remove all notifications.
Would that be possible?

**Comment by Nepeta** [comment]
Will be added in 0.5.1. Code exists now.
