### ISSUE TITLE
[Request] Do not move notifications down when "Clear All" button is off

### ISSUE THREAD

**Issue by infernoboy** [Nepeta/StackXI#67]
Right now notifications are moved down on the notification center even when the "Clear All" button is turned off. It's a simple change in the ```sxiUpdateClearAllButton``` method to prevent this:

660: ```self.view.frame = CGRectMake(self.view.frame.origin.x, (showClearAllButton) ? clearAllHeight + clearAllButtonSpacing*3 : 0, self.view.frame.size.width, self.view.frame.size.height);```

Line number correct as of commit 952a2582bcae007f431163951bf0383999dbf528

**Comment by Nepeta** [comment]
Kinda fixed in 0.5.2, will be properly fixed in a later update.
